FileNotFoundError fix
When running under Windows, the current version fails with:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/cgroup'

Added a try ... except to return false instead of failing.